<footer>
    <!-- Full-width two-column footer --> 
    <form action="index.html" method="get">
        <h2 class="plogo"><i class="ri-game-fill"></i>PowerUp</h2>
    </form>
       <!-- Column 1 -->
       <div id="footer-left">
           <ul> 
               <li>COS60004 CWA Assignment 1</li>
               <li><a href="mailto:104328146@student.swin.edu.au">104328146@student.swin.edu.au</a></li>
               <li><a href="https://www.swinburne.edu.au/" target="_blank">Swinburne University of Technology</a></li>
               <li>&#169; Levenspeil Sangalang</li>
           </ul>
        </div>
       <!-- Column 2 -->
       <div id="footer-right">
           <ul> 
                <li><a href="apply.php">Apply Now</a></li>
                <li><a href="jobs.php">Careers</a></li>
                <li><a href="about.php">About</a></li> 
                <li><a href="manage.php">Manage</a></li> 
           </ul>
        </div> 
</footer>